### ISSUE TITLE
ImportError: cannot import name 'LocalityPreservingProjection'

### ISSUE THREAD

**Issue by fmaglia** [jakevdp/lpproj#2]
I installed the package using pip, but when I try to import the 'LocalityPreservingProjection' module I obtain this error:
`ImportError: cannot import name 'LocalityPreservingProjection'`

Can I solve the problem?

Thanks in advance.

**Comment by jakevdp** [comment]
the module is named ``lpproj``... try

```python
from lpproj import LocalityPreservingProjection
```

**Comment by jakevdp** [comment]
If that doesn't work, then make certain you're using the right ``pip``; run

```
$ python -m pip install lpproj
```

If you run ``pip install``, sometimes your ``pip`` executable is not connected to your ``python`` executable.

**Comment by fmaglia** [comment]
Here the complete error:

`    Traceback (most recent call last):
  File "lpproj.py", line 4, in <module>
    from lpproj import LocalityPreservingProjection
  File "/home/federico/Desktop/lpproj.py", line 4, in <module>
    from lpproj import LocalityPreservingProjection
ImportError: cannot import name LocalityPreservingProjection`

I tried both python2 and python3, but I obtained the same error!
I also tried to reinstall the package using your previous command but I didn't solve the problem.

**Comment by jakevdp** [comment]
It looks like you're importing from a file called ``lpproj.py`` that you created on your desktop. You'll need to either remove or rename that file so that ``import lpproj`` will find this package in your python's site-packages.

If there is a name collision, packages or files in the current working directory always supersede packages installed by pip.
